AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FastAPI backend deployed with AWS SAM

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.13

Resources:
  # For CORS configuration
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - https://ee-scores-checker.vercel.app
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowCredentials: false
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: .
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          APP_ENV: prod
          DATABASE_URL: !Ref DatabaseUrl
          JWT_SECRET: !Ref JwtSecret

Parameters:
  DatabaseUrl:
    Type: String
    Default: "NOT_USED"
    NoEcho: true
  JwtSecret:
    Type: String  
    Default: "NOT_USED" 
    NoEcho: true

Outputs:
  # Output1: The
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  # Output2: Lambda function name (optional)输出2：Lambda函数名称（可选，方便调试）
  LambdaFunctionName:
    Description: "AutoComment Lambda Function Name"
    Value: !Ref ApiFunction